-- Tabela para simulação de processamento de massa de dados
-- Autor: Nelson Carlson F.
-- Data: 22-06-2026

CREATE TABLE tb_processamento_massa (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY
    ,descricao VARCHAR2(200)
    ,valor_base NUMBER(15,2)
    ,valor_atualizado NUMBER(15,2)
    ,status_processo VARCHAR2(20) DEFAULT 'PENDENTE' NOT NULL
    ,data_processamento DATE
    ,processado_por_session VARCHAR2(100)
);
